Update repositories.json
RunOnFlux/flux pull request #420
Opened 2021-12-22 14:50 UTC by kantin13

2021-12-22 15:45 UTC, TheTrunk requested changes

2021-12-22 15:45 UTC, TheTrunk commented on helpers/repositories.json
> +["yurinnick/folding-at-home:latest", "kadena/chainweb-node:latest", "zelcash/dibi-fetch:latest", "zelcash/rates-api:latest", "zelcash/kadena-chainweb-node:2.7", "presearch/node:latest", "bharathshett
Please add a space after comma

2021-12-22 15:53 UTC, kantin13 commented on helpers/repositories.json
> +["yurinnick/folding-at-home:latest", "kadena/chainweb-node:latest", "zelcash/dibi-fetch:latest", "zelcash/rates-api:latest", "zelcash/kadena-chainweb-node:2.7", "presearch/node:latest", "bharathshett
I have change

2021-12-22 16:19 UTC, TheTrunk approved these changes

2021-12-23 14:02 UTC, TheTrunk commented
Hi @kantin13 
This is a problematic application do spawn and we would prefer working on improving Flux to have sharded storage, encrypted storage first. This application will posses liability to the node owner and in the end eventually Flux team as well and we do not have a way to take down some specific content of an application in case authorities ask us. 
However it may be interesting to submit an XDAO proposal to Flux community and see what the entire community thinks about such an application on the network
https://home.runonflux.io/xdao-app

2021-12-27 10:19 UTC, closed without merging